// <auto-generated />
using System;
using BlazorShop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorShop.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230408212920_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Name = "Books",
                            Slug = "books"
                        },
                        new
                        {
                            Id = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Name = "Movies",
                            Slug = "movies"
                        },
                        new
                        {
                            Id = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Name = "Video Games",
                            Slug = "video-games"
                        });
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Joints.RolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CustomerPermission"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AdminPermission"
                        });
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfed4c40-a909-433f-ace3-adde857c1a86"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A novel about a woman's journey through the Dust Bowl era of the 1930s",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1594925043i/53138081.jpg",
                            Name = "The Four Winds",
                            Price = 25.99m,
                            Slug = "the-four-winds"
                        },
                        new
                        {
                            Id = new Guid("c0b9f4c3-e04f-446e-af08-bcd24aeae30f"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A novel about a woman who finds herself in a library between life and death, with the opportunity to try out different versions of her life",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1602190253i/52578297.jpg",
                            Name = "The Midnight Library",
                            Price = 21.99m,
                            Slug = "the-midnight-library"
                        },
                        new
                        {
                            Id = new Guid("ae240b03-c0fa-4f3a-9ba0-47fa5bffa3d2"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A novel about a robot who observes the world and learns about human behavior",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1603206535i/54120408.jpg",
                            Name = "Klara and the Sun",
                            Price = 27.99m,
                            Slug = "klara-and-the-sun"
                        },
                        new
                        {
                            Id = new Guid("c9e9d889-a43f-4ae0-997c-ef653896306b"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A novel about a man on a solo mission to save the world from extinction",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1597695864i/54493401.jpg",
                            Name = "Project Hail Mary",
                            Price = 24.99m,
                            Slug = "project-hail-mary"
                        },
                        new
                        {
                            Id = new Guid("47203461-7f10-44b6-96b1-830da85aa5f6"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A thriller about a detective investigating a murder at an isolated hotel in the Swiss Alps",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1612344489i/56935099.jpg",
                            Name = "The Sanatorium",
                            Price = 19.99m,
                            Slug = "the-sanatorium"
                        },
                        new
                        {
                            Id = new Guid("08fc14a9-df0c-4bb6-85d8-09a55fda8284"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A novel about a mother's intense desire for perfection and the consequences of her actions",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1609854219i/52476830.jpg",
                            Name = "The Push",
                            Price = 20.99m,
                            Slug = "the-push"
                        },
                        new
                        {
                            Id = new Guid("12a6481e-22d5-4bbf-aa48-3bf14a8abc3a"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A non-fiction book about the woman who helped develop CRISPR gene-editing technology",
                            ImageUrl = "https://m.media-amazon.com/images/I/41an9tLSfBL._SX327_BO1,204,203,200_.jpg",
                            Name = "The Code Breaker",
                            Price = 28.99m,
                            Slug = "the-code-breaker"
                        },
                        new
                        {
                            Id = new Guid("608aa221-6a68-4197-8e32-ef53a2bc6bbb"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A memoir about a woman's relationship with her Korean mother and the grieving process after her mother's death",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1601937850i/54814676.jpg",
                            Name = "Crying in H Mart",
                            Price = 22.99m,
                            Slug = "crying-in-h-mart"
                        },
                        new
                        {
                            Id = new Guid("4b75fc46-38ac-4c6b-879b-2c43a44a6853"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A novel about the intersection of the digital and real worlds",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1601474686i/53733106.jpg",
                            Name = "No One Is Talking About This",
                            Price = 23.99m,
                            Slug = "no-one-is-talking-about-this"
                        },
                        new
                        {
                            Id = new Guid("89de1450-e9b2-4caf-ad05-ac8a6f1c120c"),
                            CategoryId = new Guid("73fc413d-9817-4428-9f34-4c5f80f4f3dd"),
                            Description = "A non-fiction book about the Sackler family and their role in the opioid crisis",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1611952534i/43868109.jpg",
                            Name = "Empire of Pain",
                            Price = 26.99m,
                            Slug = "empire-of-pain"
                        },
                        new
                        {
                            Id = new Guid("83436c27-2f26-486b-8996-587f524a0ebf"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A drama film about a woman who embarks on a journey through the American West after the economic collapse of a company town",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a5/Nomadland_poster.jpeg",
                            Name = "Nomadland",
                            Price = 14.99m,
                            Slug = "nomadland"
                        },
                        new
                        {
                            Id = new Guid("0f088068-6ad6-4d59-bd7c-53b9bf02242b"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A drama film about a Korean American family who moves to Arkansas in search of the American Dream",
                            ImageUrl = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRO2Ubq5Jw9K26Yf2FIs5Hn4qAmBw9iN5f33KXfOS9-7SrDji-a",
                            Name = "Minari",
                            Price = 14.99m,
                            Slug = "minari"
                        },
                        new
                        {
                            Id = new Guid("c1f325cf-b109-458b-8072-16ffee255759"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A historical legal drama film about the trial of seven defendants charged with conspiracy and inciting riots at the 1968 Democratic National Convention in Chicago",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpYXw7g_VNc6BgTpeO_teA9iFcaz56RNKE4yke-CfHLulmC4mC",
                            Name = "The Trial of the Chicago 7",
                            Price = 14.99m,
                            Slug = "the-trial-of-the-chicago-7"
                        },
                        new
                        {
                            Id = new Guid("3e30c1b8-61b5-48d9-82a5-a67bbe187c7a"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A drama film about a recording session with Ma Rainey and her band in 1920s Chicago",
                            ImageUrl = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQbwaPsGL1aZVMgWOFxy3vTTEKm-Mdsqr4g5ZH_EOVLTXqVKOEU",
                            Name = "Ma Rainey's Black Bottom",
                            Price = 14.99m,
                            Slug = "ma-raineys-black-bottom"
                        },
                        new
                        {
                            Id = new Guid("bf1bd910-e2cf-463b-b03b-a11fed145943"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A thriller film about a woman seeking revenge against those who wronged her best friend",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt0E2TEuop7cpx_XAPCUh0iWdoPBqk4ykJKCpfNGFwlwIf-yTx",
                            Name = "Promising Young Woman",
                            Price = 14.99m,
                            Slug = "promising-young-woman"
                        },
                        new
                        {
                            Id = new Guid("7cd04ec5-a9ef-4cc1-bcda-74145b5828cb"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A drama film about a heavy metal drummer who begins to lose his hearing",
                            ImageUrl = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRBan44FQYlb0XJ-54n54uUojA9QxH7s6lhppT9mSsLOGRcSnai",
                            Name = "Sound of Metal",
                            Price = 14.99m,
                            Slug = "sound-of-metal"
                        },
                        new
                        {
                            Id = new Guid("b72a33a1-1ea3-4c8a-9fd3-468ba5f69015"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A drama film about a man with dementia and his daughter's struggles to care for him",
                            ImageUrl = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRY6PkexuVznH6FEgo0by3HRofrGLE9cK6MoC2SiyZHponQb3oY",
                            Name = "The Father",
                            Price = 14.99m,
                            Slug = "the-father"
                        },
                        new
                        {
                            Id = new Guid("7314eeda-f664-46b3-9620-ee6d6340d40d"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "An animated film about a middle school music teacher who dreams of being a jazz musician",
                            ImageUrl = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSWzrHSIZFXCrHAgxd2omcvTVB5jqPkmCVemT0XYPj-CWgRoMs_",
                            Name = "Soul",
                            Price = 14.99m,
                            Slug = "soul"
                        },
                        new
                        {
                            Id = new Guid("b44f2367-578e-4e21-bfe0-ed310bc18722"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A war drama film about a group of Vietnam War veterans who return to the country in search of treasure and their fallen squad leader's remains",
                            ImageUrl = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ6Y8U3gK1QlfBmjVh_mx9-Ll_YzI3d6K2DQIMQQkUxLuew5K7N",
                            Name = "Da 5 Bloods",
                            Price = 14.99m,
                            Slug = "da-5-bloods"
                        },
                        new
                        {
                            Id = new Guid("c12bac57-0714-4599-837c-dc3a9d02ce66"),
                            CategoryId = new Guid("174eb448-e412-4114-bfe2-0ff3b1a12291"),
                            Description = "A science fiction action film about a secret agent who must prevent World War III through time inversion",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4o4eBZdZWCR0iNFjiu1p4BKAIwIOkm_tZr3A-WUu4IAAcrq57",
                            Name = "Tenet",
                            Price = 14.99m,
                            Slug = "tenet"
                        },
                        new
                        {
                            Id = new Guid("2157c735-30ff-4b97-8472-024d07e44306"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "An open-world action-adventure game set in a post-apocalyptic Hyrule",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Price = 59.99m,
                            Slug = "the-legend-of-zelda-breath-of-the-wild"
                        },
                        new
                        {
                            Id = new Guid("547ed959-f428-4f0e-b744-e86fd4ac5cac"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "An action game set in a post-apocalyptic world where the player must deliver supplies and build connections between isolated cities",
                            ImageUrl = "https://cdn1.epicgames.com/offer/0a9e3c5ab6684506bd624a849ca0cf39/EGS_DeathStrandingDirectorsCut_KOJIMAPRODUCTIONS_S4_1200x1600-5f99e16507795f9b497716b470cfd876",
                            Name = "Death Stranding",
                            Price = 49.99m,
                            Slug = "death-stranding"
                        },
                        new
                        {
                            Id = new Guid("3d7bfbb1-51ef-4715-b901-04479f2b7764"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "A survival horror game set in a post-apocalyptic United States where the player must navigate through dangerous environments and fight off infected creatures and hostile human factions",
                            ImageUrl = "https://image.api.playstation.com/vulcan/img/rnd/202010/2618/w48z6bzefZPrRcJHc7L8SO66.png",
                            Name = "The Last of Us Part II",
                            Price = 59.99m,
                            Slug = "the-last-of-us-part-ii"
                        },
                        new
                        {
                            Id = new Guid("7592b529-1d68-4eba-81b3-3935b0b656cf"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "An action-adventure game set in 13th century Japan where the player takes on the role of a samurai warrior fighting against invading Mongol forces",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/b6/Ghost_of_Tsushima.jpg",
                            Name = "Ghost of Tsushima",
                            Price = 49.99m,
                            Slug = "ghost-of-tsushima"
                        },
                        new
                        {
                            Id = new Guid("0af6ec9d-9426-472a-9d8b-a5c44ce072a3"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "A roguelike action game where the player takes on the role of Prince Zagreus attempting to escape from the underworld",
                            ImageUrl = "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71FjVhf-SlL._AC_UF894,1000_QL80_.jpghttps://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71FjVhf-SlL._AC_UF894,1000_QL80_.jpg",
                            Name = "Hades",
                            Price = 24.99m,
                            Slug = "hades"
                        },
                        new
                        {
                            Id = new Guid("74a6134c-dea6-4c3c-8312-a11bbc9f36d1"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "A life simulation game where the player moves to a deserted island and builds a community with anthropomorphic animals",
                            ImageUrl = "https://animal-crossing.com/new-horizons/assets/img/share-tw.jpg",
                            Name = "Animal Crossing: New Horizons",
                            Price = 59.99m,
                            Slug = "animal-crossing-new-horizons"
                        },
                        new
                        {
                            Id = new Guid("e4ae1d55-3bc5-4d69-90b2-cbf08b214b0d"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "A first-person shooter game where the player takes on the role of the Doom Slayer and battles demons from hell",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/9d/Cover_Art_of_Doom_Eternal.png",
                            Name = "Doom Eternal",
                            Price = 59.99m,
                            Slug = "doom-eternal"
                        },
                        new
                        {
                            Id = new Guid("ebcad60a-f4a8-4eab-aad0-d803b1322756"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "A battle royale party game where the player competes with up to 60 players in various obstacle courses",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Fall_Guys_cover.jpg/220px-Fall_Guys_cover.jpg",
                            Name = "Fall Guys: Ultimate Knockout",
                            Price = 19.99m,
                            Slug = "fall-guys-ultimate-knockout"
                        },
                        new
                        {
                            Id = new Guid("628c9f16-e7ca-47be-b790-b90c7d5b0d71"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "An action-adventure game where the player takes on the role of Miles Morales as he becomes the new Spider-Man and fights crime in New York City",
                            ImageUrl = "https://image.api.playstation.com/vulcan/ap/rnd/202008/1020/T45iRN1bhiWcJUzST6UFGBvO.png",
                            Name = "Marvel's Spider-Man: Miles Morales",
                            Price = 49.99m,
                            Slug = "spider-man-miles-morales"
                        },
                        new
                        {
                            Id = new Guid("1ec8e313-0612-4809-8753-16ab79ba5afa"),
                            CategoryId = new Guid("defb6999-12cc-49df-bdae-1761fb589507"),
                            Description = "An open-world role-playing game set in a dystopian future where the player takes on the role of a mercenary navigating through the criminal underworld of Night City",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Cyberpunk_2077_box_art.jpg/220px-Cyberpunk_2077_box_art.jpg",
                            Name = "Cyberpunk 2077",
                            Price = 59.99m,
                            Slug = "cyberpunk-2077"
                        });
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmationCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewEmailConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTfaEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Comment", b =>
                {
                    b.HasOne("BlazorShop.Server.Data.Entities.Product", null)
                        .WithMany("Comments")
                        .HasForeignKey("ProductId");

                    b.HasOne("BlazorShop.Server.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Joints.RolePermission", b =>
                {
                    b.HasOne("BlazorShop.Server.Data.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.Server.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Product", b =>
                {
                    b.HasOne("BlazorShop.Server.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Security", b =>
                {
                    b.HasOne("BlazorShop.Server.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Session", b =>
                {
                    b.HasOne("BlazorShop.Server.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.User", b =>
                {
                    b.HasOne("BlazorShop.Server.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BlazorShop.Server.Data.Entities.Product", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
